### ISSUE TITLE
Customize Carousel Buttons 

### ISSUE THREAD

**Issue by ycaquino** [ycaquino/ASC#1]
Customize buttons so they are visible by the user

**Comment by Harshit850** [comment]
@ycaquino only need to modify the carousel so they are clearly visible?

**Comment by Harshit850** [comment]
@ycaquino only need to modify the carousel slide button so they are clearly visible?

**Comment by Harshit850** [comment]
done @ycaquino

**Comment by ycaquino** [comment]
Thanks!
